--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/mehrbod1gamer/trashCan
branches:
- main
projects:
  trashCan:
    path: ""
    libs:
      - src: muqsit/InvMenu/InvMenu
        version: ^3.1.1
    
...
